CREATE DATABASE IF NOT EXISTS dog_db;
USE dog_db;

CREATE TABLE IF NOT EXISTS dogs (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    breed VARCHAR(50) NOT NULL,
    age VARCHAR(50) NOT NULL,
    address VARCHAR(100) NOT NULL,
    color VARCHAR(30),
    height VARCHAR(20),
    weight VARCHAR(20),
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

